import type { enUS } from './en-US'

type ResourceShape<T> = { [K in keyof T]: T[K] extends object ? ResourceShape<T[K]> : string }

export const zhCN: ResourceShape<typeof enUS> = {
  common: {
    actions: { approve: '批准', approveAndExecute: '批准并执行', approveOnly: '仅批准', reject: '拒绝', cancel: '取消', back: '返回', create: '创建', archive: '归档', open: '打开', save: '保存', retry: '重试', testConnection: '测试连接', startAgent: '启动 Agent', validateWorkspace: '验证工作区', reviewApprovals: '查看审批', openApprovalCenter: '打开审批中心', openReport: '打开报告', resumeApprovedExecution: '恢复已批准执行', showTechnicalDetails: '显示技术详情', hideTechnicalDetails: '隐藏技术详情' },
    labels: { loading: '加载中', error: '错误', configured: '已配置', notConfigured: '未配置', unknown: '未知', operator: '操作员', systemHealth: '系统健康', allTimesUtc: '所有时间均为 UTC', revisionUnavailable: '版本修订不可用', provider: '提供商', model: '模型', status: '状态', connection: '连接', credentialConfigured: '凭据已配置', noCredentialRequired: '无需凭据', workspace: '工作区', project: '项目', task: '任务', goal: '目标', title: '标题', description: '描述', environment: '环境', capabilities: '能力', permission: '权限', risk: '风险', version: '版本', steps: '步骤', events: '事件', artifacts: '产物', actor: '执行者', correlationId: '关联 ID', taskId: '任务 ID', approvalId: '审批 ID', planId: '计划 ID', command: '命令', taskState: '任务状态', approvalState: '审批状态', executionInitiation: '执行启动', authorityValidation: '权限校验', lastCheckpoint: '最近检查点', plan: '计划', evidence: '证据', observation: '观察结果', execution: '执行' },
    states: { empty: '暂无内容', noData: '暂无数据', noTasks: '暂无任务', noApprovals: '暂无待审批项', noEvidence: '暂无证据记录', noExecutions: '暂无执行记录', noPlan: '无计划', noValidatedPlan: '暂无已验证计划。', noResult: '暂无结果摘要', noParameters: '无参数' },
  },
  shell: { brandSub: 'AI Agent 运维控制台', eyebrow: '企业级 AI Agent 运维控制台', systemOperational: '系统运行正常' },
  navigation: { dashboard: '仪表盘', agent: 'Agent', projects: '项目', tasks: '任务', approvals: '审批', evidence: '证据', audit: '审计', reports: '报告', diagnostics: '系统诊断', language: '语言', english: 'English', chinese: '中文' },
  dashboard: { eyebrow: '运行概览', title: '仪表盘', subtitle: '了解 Agent 正在规划、等待审批和执行的内容。', reviewApprovals: '查看审批', totalTasks: '任务总数', pendingApprovals: '待审批', running: '运行中', passed: '通过', failed: '失败', provider: 'LLM 提供商', openAiCompatible: 'OpenAI 兼容', mock: 'Mock', providerNotConfigured: '尚未配置真实 AI 提供商', trackedCount: '已跟踪 {{count}} 项', connection: '连接', testing: '测试中…', testConnection: '测试连接', credentialConfigured: '凭据已配置', noCredentialRequired: '无需凭据', recentTasks: '最近任务', approvalQueue: '审批队列', approvalWaiting: '等待 {{count}} 项', approvalRequestsWaiting: '暂无待处理的审批请求。', openApprovalCenter: '打开审批中心', recentActivity: '最近活动', auditTrail: '审计轨迹', planWaiting: '计划正在等待人工审批', planner: 'Release v2.0 Verification · planner-agent', planValidationCompleted: '计划校验完成', operationsPassed: '所有请求的操作均通过策略校验', justNow: '刚刚', minutesAgo: '{{count}} 分钟前', demoBanner: '演示数据预览——连接 FastAPI 后端以使用实时任务数据。' },
  projects: { eyebrow: '本地执行边界', title: '项目', subtitle: '将每个新任务绑定到经过验证的工作区和明确的能力策略。', local: '本地项目', configured: '已配置 {{count}} 个', createProject: '创建项目', empty: '暂无本地项目。', name: '项目名称', workspacePath: '工作区路径', workspacePlaceholder: 'D:\\AgentProjects\\Example', validateWorkspace: '验证工作区', environment: '环境', allowedCapabilities: '允许的能力', defaultDeny: '不会隐式启用任何能力。', recentTask: '最近任务 {{count}} 项', recentTasks: '最近任务 {{count}} 项', openProject: '打开项目', active: '活跃', archived: '已归档', projectCreated: '项目已创建。', creationFailed: '项目创建失败。', validationFailed: '工作区验证失败。', validWorkspace: '有效工作区：{{workspace}}' },
  projectDetail: { backToProjects: '返回项目', unavailable: '项目详情不可用。', eyebrow: '项目执行权限', noDescription: '暂无描述。', archived: '已归档项目', archivedMessage: '历史记录仍可查看，但已禁止创建新任务和执行。', boundary: '项目边界', canonicalWorkspace: '规范工作区', configVersion: '配置版本', allowedCapabilities: '允许的能力', noCapabilities: '未启用任何能力（默认拒绝）。', createTask: '创建任务', taskTitle: '标题', taskGoal: '目标', taskCreated: '任务已创建。', taskCreationFailed: '任务创建失败。', archiveProject: '归档项目', recentTasks: '最近任务', shown: '显示 {{count}} 项', noTasks: '该项目暂无任务。' },
  tasks: { detailEyebrow: '任务详情', backToDashboard: '返回仪表盘', goal: '目标', workspace: '工作区', created: '创建时间', agent: 'Agent', releaseVerificationAgent: '发布验证 Agent', openReport: '打开报告', generatedPlan: '生成的计划', version: '版本', evidence: '证据', artifacts: '{{count}} 项产物', evidenceAfter: '批准执行后将显示证据。', toolExecutions: '工具执行', recorded: '已记录 {{count}} 项', noExecution: '尚未开始工具执行。', noResult: '暂无结果摘要', auditHistory: '审计历史', events: '{{count}} 个事件' },
  approvals: { eyebrow: '人工控制点', title: '审批中心', subtitle: '在 Agent 获得执行权限前，准确审查它将执行的内容。', pending: '待处理', decisionFailed: '决策失败', executeNotice: 'Agent 将执行以下内容。', reviewNotice: '请检查能力、解析后的工具、规范化参数和注册表绑定。', resolvedPlan: '解析后的计划', steps: '{{count}} 个步骤', resolvedTool: '解析工具', normalized: '规范化参数', fingerprint: '注册表指纹：', bindingNotice: '能力、工具、参数和注册表语义均已绑定到审批。', aggregateRisk: '总体风险：', boundary: '权限边界', workspaceOnly: '仅限工作区', noShell: '无 Shell 访问 · 不执行破坏性操作 · 不读取秘密文件', requestedBy: '请求者', auditNote: '你的决定将记录在审计日志中。', agentWorkspaceNote: '此审批必须在 Agent 工作区完成，才能启动受治理的执行。', approvalOnlyNote: '在此处批准只会记录审批，不会启动 Agent 执行。', openInAgentWorkspace: '在 Agent 工作区打开', empty: '暂无待审批项。计划通过校验后，任务会显示在这里。' },
  agent: { eyebrow: '仓库分析 Agent', title: 'Agent 工作区', description: '在人工审批下执行受治理的仓库分析。', currentRun: '当前 Agent 运行', noCurrentRun: '当前没有 Agent 运行', createToBegin: '创建一个 Agent 任务以开始。', planVersion: '计划', planning: '规划中...', planningNext: 'Agent 正在准备受治理的计划。', waitingNext: '审查计划和请求的能力后再执行。', runningNext: 'Agent 正在执行已批准的受治理步骤。', successNext: 'Agent 已完成运行。请查看结论和证据。', failedNext: 'Agent 运行失败。请查看时间线和错误详情。', startNext: '启动 Agent 以开始受治理的运行。', goalComposer: '目标编辑器', authorityRequired: '需要项目权限', selectProject: '选择项目', goal: '目标', goalPlaceholder: '检查该项目是否已准备好发布。', start: '启动 Agent', starting: '规划中...', timeline: 'Agent 时间线', authoritativeLifecycle: '权威生命周期', timelineEmpty: '启动 Agent 后，这里会显示已持久化的计划、审批、执行、观察结果和证据。', execution: '执行', governedExecution: '受治理的执行', recoveryDescription: '当前计划已有权威审批。若执行尚未开始，可通过组合审批命令恢复。', refreshError: '无法刷新 Agent 状态', status: { created: '已创建', planning: '规划中...', waitingApproval: '等待审批', running: '运行中', completed: '已完成', failed: '失败', cancelled: '已取消', unknown: '未知' } },
  agentApproval: { required: '需要审批', planVersion: '计划 v{{version}}', reviewPlan: '执行前请审查这份受治理的计划。', selectedWorkspace: '所选项目工作区', risk: '风险：仅允许受治理的只读能力，不授予任意 Shell 执行权限。', approving: '正在批准…', rejectReason: '计划需要操作员修改', reject: '拒绝' },
  agentPlan: { planVersion: '计划 v{{version}}', summaryFallback: '暂无计划摘要', planId: '计划 ID', noPlan: '无计划' },
  agentReport: { title: '证据支持的报告', completed: '已完成', failed: '失败', rejected: '已拒绝', evidence: '证据', unavailable: '证据不可用。' },
  analyst: { title: 'AI 项目分析', succeeded: '分析已完成', notRequested: '尚未请求分析', pending: '分析等待中', generating: '正在生成分析', failed: '分析失败', failedTitle: '分析不可用', failedDescription: '受治理的执行证据仍然可用；系统未接受任何 Analyst 结论。', notRequestedDescription: '此历史任务没有基于证据的 Analyst 报告。', pendingDescription: '已有终态执行记录，分析正在排队。', generatingDescription: 'Analyst 正在评估有界的持久化证据。', overallAssessment: '整体评估', releaseRecommendation: '发布建议', keyFindings: '关键发现', nextActions: '下一步行动', limitations: '限制与未知项', rationale: '判断依据', evidenceRefs: '证据引用', recommendedAction: '建议操作', noFindings: '没有报告实质性发现。', noNextActions: '没有报告其他行动。', noLimitations: '没有报告其他限制。', evidenceCoverage: '已引用 {{referenced}} / {{available}} 条证据记录', evidenceSufficiency: '证据充分性', truncated: '输入已按上限截断', overall: { HEALTHY: '健康', AT_RISK: '存在风险', BLOCKED: '阻塞', UNKNOWN: '未知' }, recommendation: { READY: '可以发布', READY_WITH_CONDITIONS: '有条件可以发布', NOT_READY: '暂不建议发布', INSUFFICIENT_EVIDENCE: '证据不足' }, sufficiency: { SUFFICIENT: '证据充分', PARTIAL: '部分证据', INSUFFICIENT: '证据不足' }, severity: { BLOCKER: '阻塞', HIGH: '高', MEDIUM: '中', LOW: '低', INFO: '信息' } },
  timeline: { title: 'Agent 时间线', events: '{{count}} 个事件', noEvents: '暂无已持久化的 Agent 事件。', goalReceived: '已收到目标', planning: '规划中', planCreated: '计划已创建', waitingApproval: '等待审批', approved: '已批准', approvalRejected: '审批已拒绝', stepStarted: '步骤已开始', toolExecutionCompleted: '工具执行完成', observationRecorded: '已记录观察结果', stepFailed: '步骤失败', replanning: '重新规划', successorPlanCreated: '后继计划已创建', completed: '已完成', failed: '失败', unknownEvent: '技术事件' },
  report: { finalEyebrow: '最终验证结果', title: '就绪度报告', backToTask: '返回任务', releaseReadiness: '发布就绪度', completedChecks: '已完成检查', failedChecks: '失败检查', evidenceArtifacts: '证据产物', auditEvents: '审计事件', evidenceReferences: '证据引用', traceableArtifacts: '可追溯产物', noEvidenceArtifacts: '尚未生成证据产物。', auditSummary: '审计摘要', immutableRecord: '不可变记录', eventsRecorded: '已记录 {{count}} 个事件', traceableLifecycle: '任务生命周期、计划校验、审批和执行事件均可追溯。', toolExecutions: '{{count}} 次工具执行', governedExecutions: '所有执行均通过 Tool Gateway 受治理。' },
  diagnostics: { eyebrow: '可运维性', title: '系统诊断', loading: '正在加载系统诊断…', unable: '无法加载系统诊断', overall: '总体健康状态', backend: '后端', database: '数据库', provider: '提供商', credentials: '凭据', plannerProvider: 'Planner 提供商', analystProvider: 'Analyst 提供商', analystMode: 'Analyst 分析模式', durableEyebrow: '持久化生命周期', latestCommand: '最近审批命令', agentCommand: 'Agent 批准并执行', globalCommand: '全局审批', command: '命令：', taskState: '任务状态：', approvalState: '审批状态：', executionInitiation: '执行启动：', authorityValidation: '权限校验：', taskId: '任务 ID：', plan: '计划：', approvalId: '审批 ID：', lastCheckpoint: '最近检查点：', correlationId: '关联 ID：', failureCategory: '失败类别：' },
  provider: { success: '连接成功', notTested: '尚未测试连接', failed: '连接失败' },
  status: { task: { created: '已创建', planning: '规划中', waitingApproval: '等待审批', running: '运行中', success: '成功', failed: '失败', cancelled: '已取消' }, approval: { pending: '待处理', approved: '已批准', rejected: '已拒绝', cancelled: '已取消' }, execution: { success: '成功', failed: '失败', rejected: '已拒绝' }, health: { healthy: '健康', degraded: '降级', unhealthy: '不健康', unknown: '未知' }, risk: { low: '低', medium: '中', high: '高' }, unknown: '未知' },
  capabilities: { repository_state: { label: '读取仓库状态', description: '只读检查所选仓库，不会修改文件。' }, project_metadata: { label: '读取项目元数据', description: '仅读取该项目允许的应用元数据。' }, test_verification: { label: '运行项目测试', description: '运行预定义的受治理测试配置，不授予任意 Shell 执行权限。' }, unknown: { label: '应用能力', description: '已注册的应用能力。' } },
  permissions: { safeRead: '安全读取', approvedExec: '批准后执行', denied: '拒绝' },
}
