import { AlertTriangle, Ban, CheckCircle2, FileText, ShieldCheck, XCircle } from 'lucide-react'
import { PermissionPill, RiskPill, StatusPill } from '../components/StatusPill'
import { PanelTitle } from './Dashboard'
import type { ApprovalQueueItem } from '../types'

export function Approvals({ approvals, onApprove, onReject, onCancel }: { approvals: ApprovalQueueItem[]; onApprove: (id: string) => void; onReject: (id: string) => void; onCancel: () => void }) {
  const selected = approvals[0]
  return <section className="page-stack"><div className="page-heading"><div><div className="eyebrow">HUMAN CONTROL POINT</div><h2>Approval Center</h2><p>Review exactly what the Agent will execute before it receives permission.</p></div><div className="approval-count"><span>{approvals.length}</span> pending</div></div>{selected ? <div className="approval-layout"><div className="panel plan-panel"><div className="callout"><ShieldCheck size={22} /><div><strong>This is what the Agent will execute.</strong><span>Review the plan, scope, permissions, and intended evidence before approving.</span></div></div><PanelTitle title={`Generated plan · Version ${selected.plan_version}`} action={`${selected.plan_json.steps.length} steps`} /><div className="plan-list">{selected.plan_json.steps.map((step, index) => <div className="plan-step" key={step.step_id}><span className="step-number">{index + 1}</span><div className="step-tool"><FileText size={17} /><strong>{step.tool}</strong><span>{step.action}</span><PermissionPill value={step.permission_level} /></div><div className="step-risk"><span>Risk level</span><RiskPill value={step.risk_level} /><p>{step.permission_level === 'APPROVED_EXEC' ? 'Runs a predefined test profile in the governed workspace.' : 'Read-only access to approved project metadata.'}</p></div><div className="step-evidence"><span>Intended evidence</span><strong>{step.tool === 'test_run' ? 'test-results.json' : `${step.tool}-summary.json`}</strong></div></div>)}</div><div className="plan-footer"><span><AlertTriangle size={15} /> The plan is deterministic and version-bound.</span><strong>Aggregate risk: <RiskPill value="Medium" /></strong></div></div><aside className="panel decision-panel"><div className="decision-header"><StatusPill status="WAITING_APPROVAL" /><span>Plan v{selected.plan_version}</span></div><h3>{selected.task_title}</h3><p className="muted">Requested by {selected.requested_by}</p><div className="boundary"><span>Permission boundary</span><strong>Workspace-scoped only</strong><small>No shell access · no destructive actions · no secret files</small></div><div className="permission-list"><div><PermissionPill value="SAFE_READ" /><span>Repository and file metadata</span></div><div><PermissionPill value="APPROVED_EXEC" /><span>Predefined smoke test</span></div></div><div className="decision-actions"><button className="button button-approve" onClick={() => onApprove(selected.id)}><CheckCircle2 size={16} /> Approve</button><button className="button button-danger" onClick={() => onReject(selected.id)}><XCircle size={16} /> Reject</button><button className="button button-muted" onClick={onCancel}><Ban size={16} /> Cancel task</button></div><p className="audit-note">Your decision will be recorded in the audit log.</p></aside></div> : <div className="panel empty-state large">No pending approvals. Tasks will appear here after their plans are validated.</div>}</section>
}
