import { ArrowRight, CheckCircle2, Clock3, ListTodo, ShieldAlert, XCircle } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { StatusPill, RiskPill } from '../components/StatusPill'
import { providerStatusKey } from '../i18n/status'
import type { ApprovalQueueItem, ProviderStatus, TaskSummary } from '../types'

export function Dashboard({ tasks, approvals, providerStatus, testingProvider, onTestProvider, onTask, onApprovals }: { tasks: TaskSummary[]; approvals: ApprovalQueueItem[]; providerStatus: ProviderStatus; testingProvider: boolean; onTestProvider: () => void; onTask: (id: string) => void; onApprovals: () => void }) {
  const { t, i18n } = useTranslation()
  const running = tasks.filter(t => t.status === 'RUNNING').length
  const passed = tasks.filter(t => t.status === 'SUCCESS').length
  const failed = tasks.filter(t => t.status === 'FAILED').length
  return <section className="page-stack"><div className="page-heading"><div><div className="eyebrow">{t('dashboard.eyebrow')}</div><h2>{t('dashboard.title')}</h2><p>{t('dashboard.subtitle')}</p></div><button className="button button-primary" onClick={onApprovals}>{t('dashboard.reviewApprovals')} <ArrowRight size={15} /></button></div>
    <div className="metric-grid"><Metric icon={ListTodo} label={t('dashboard.totalTasks')} value={tasks.length} tone="blue" /><Metric icon={ShieldAlert} label={t('dashboard.pendingApprovals')} value={approvals.length} tone="amber" /><Metric icon={Clock3} label={t('dashboard.running')} value={running} tone="green" /><Metric icon={CheckCircle2} label={t('dashboard.passed')} value={passed} tone="green" /><Metric icon={XCircle} label={t('dashboard.failed')} value={failed} tone="red" /></div>
    <div className="panel provider-panel"><div><div className="eyebrow">{t('dashboard.provider')}</div><strong>{providerStatus.configured && providerStatus.provider === 'openai-compatible' ? t('dashboard.openAiCompatible') : providerStatus.configured && providerStatus.provider === 'mock' ? t('dashboard.mock') : t('dashboard.providerNotConfigured')}</strong><span>{providerStatus.model}</span><span>{providerStatus.configured ? (providerStatus.credential_configured ? t('dashboard.credentialConfigured') : t('dashboard.noCredentialRequired')) : t('dashboard.providerNotConfigured')}</span></div><div className="provider-state"><span className={`health-dot ${providerStatus.connection_status.replace(' ', '_')}`} />{t(providerStatusKey(providerStatus.connection_status))}</div><button className="button button-secondary" disabled={testingProvider} onClick={onTestProvider}>{testingProvider ? t('dashboard.testing') : t('dashboard.testConnection')}</button></div>
    <div className="content-grid dashboard-grid"><div className="panel"><PanelTitle title={t('dashboard.recentTasks')} action={t('dashboard.trackedCount', { count: tasks.length })} /><div className="task-table">{tasks.map(task => <button className="task-row" onClick={() => onTask(task.id)} key={task.id}><div className="task-icon"><ListTodo size={16} /></div><div className="task-name"><strong>{task.title}</strong><span>{task.goal}</span></div><StatusPill status={task.status} /><RiskPill value={task.status === 'WAITING_APPROVAL' ? 'Medium risk' : 'Low risk'} /><time>{new Date(task.updated_at).toLocaleString(i18n.language)}</time><ArrowRight size={16} /></button>)}</div></div><div className="panel approval-callout"><PanelTitle title={t('dashboard.approvalQueue')} action={t('dashboard.approvalWaiting', { count: approvals.length })} /><div className="approval-list">{approvals.slice(0, 3).map(item => <button onClick={onApprovals} className="approval-row" key={item.id}><div><strong>{item.task_title}</strong><span>Plan version {item.plan_version} · {item.plan_json.steps.length} {t('common.labels.steps')}</span></div><StatusPill status="WAITING_APPROVAL" /></button>)}</div>{approvals.length === 0 && <Empty text={t('dashboard.approvalRequestsWaiting')} />}<button className="text-button" onClick={onApprovals}>{t('dashboard.openApprovalCenter')} <ArrowRight size={14} /></button></div></div>
    <div className="panel activity-panel"><PanelTitle title={t('dashboard.recentActivity')} action={t('dashboard.auditTrail')} /><div className="activity-row"><span className="activity-dot amber" /><div><strong>{t('dashboard.planWaiting')}</strong><span>{t('dashboard.planner')}</span></div><time>{t('dashboard.justNow')}</time></div><div className="activity-row"><span className="activity-dot green" /><div><strong>{t('dashboard.planValidationCompleted')}</strong><span>{t('dashboard.operationsPassed')}</span></div><time>{t('dashboard.minutesAgo', { count: 4 })}</time></div></div>
  </section>
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof ListTodo; label: string; value: number; tone: string }) { return <div className="metric"><span className={`metric-icon ${tone}`}><Icon size={18} /></span><div><span>{label}</span><strong>{value}</strong></div></div> }
export function PanelTitle({ title, action }: { title: string; action?: string }) { return <div className="panel-title"><h3>{title}</h3>{action && <span>{action}</span>}</div> }
export function Empty({ text }: { text: string }) { return <div className="empty-state">{text}</div> }
