import { useEffect, useState } from 'react'
import { api } from '../api/client'
import type { Diagnostics as DiagnosticsData, HealthState } from '../types'

export function Diagnostics() {
  const [data, setData] = useState<DiagnosticsData | null>(null)
  const [error, setError] = useState<string | null>(null)
  useEffect(() => { void api.getDiagnostics().then(setData).catch((reason: Error) => setError(reason.message)) }, [])
  if (error) return <section className="panel"><h2>System diagnostics</h2><p role="alert">Unable to load diagnostics: {error}</p></section>
  if (!data) return <section className="panel"><h2>System diagnostics</h2><p>Loading diagnostics…</p></section>
  const health = (label: string, value: HealthState) => <div className="stat-row" key={label}><span>{label}</span><strong>{value}</strong></div>
  const provenance = data.command_provenance
  const commandLabel = provenance?.command_kind === 'AGENT_APPROVE_AND_EXECUTE' ? 'Agent Approve & Execute' : provenance?.command_kind === 'GLOBAL_APPROVAL' ? 'Global Approval' : provenance?.command_kind
  return <section className="page-stack"><section className="panel"><div className="section-heading"><div><div className="eyebrow">OPERABILITY</div><h2>System diagnostics</h2></div><strong>{data.health.overall}</strong></div><p>{data.identity.product} {data.identity.version} · {data.identity.revision ?? 'Revision unavailable'}</p><div className="stats-grid">{health('Backend', data.health.backend)}{health('Database', data.health.database)}{health('Provider', data.health.provider)}</div><p>Provider: {data.provider.provider} · {data.provider.model} · {data.provider.connection}</p><p>Credentials: {data.provider.credential_configured ? 'Configured' : 'Not configured'}</p></section>{provenance && <section className="panel" data-testid="command-provenance"><div className="section-heading"><div><div className="eyebrow">DURABLE LIFECYCLE</div><h2>Latest approval command</h2></div><strong>{commandLabel}</strong></div><div className="stats-grid"><div className="stat-row"><span>Command:</span><strong>{commandLabel}</strong></div><div className="stat-row"><span>Task state:</span><strong>{provenance.task_state}</strong></div><div className="stat-row"><span>Approval state:</span><strong>{provenance.approval_state ?? 'Unknown'}</strong></div><div className="stat-row"><span>Execution initiation:</span><strong>{provenance.execution_initiation}</strong></div><div className="stat-row"><span>Authority validation:</span><strong>{provenance.authority_validation ?? 'Unknown'}</strong></div></div><p>Task ID: <code>{provenance.task_id}</code></p><p>Plan: <code>{provenance.plan_id ?? 'Unavailable'}</code> · version {provenance.plan_version ?? 'Unavailable'}</p><p>Approval ID: <code>{provenance.approval_id ?? 'Unavailable'}</code></p><p>Last checkpoint: <code>{provenance.last_checkpoint}</code></p><p>Correlation ID: <code>{provenance.correlation_id}</code></p>{provenance.failure_category && <p role="status">Failure category: <code>{provenance.failure_category}</code></p>}</section>}</section>
}
