import { ArrowLeft, FileSearch, History, Play } from 'lucide-react'
import { StatusPill } from '../components/StatusPill'
import { Timeline } from '../components/Timeline'
import { PanelTitle } from './Dashboard'
import type { TaskDetail as Detail } from '../types'

export function TaskDetail({ detail, onBack, onReport }: { detail: Detail; onBack: () => void; onReport: () => void }) {
  const task = detail.task; const plan = detail.plans[0]
  return <section className="page-stack">
    <button className="back-button" onClick={onBack}><ArrowLeft size={15} /> Back to dashboard</button>
    <div className="page-heading task-heading"><div><div className="eyebrow">TASK DETAIL</div><h2>{task.title}</h2><p>{task.goal}</p></div><StatusPill status={task.status} /></div>
    <div className="panel"><div className="task-meta"><div><span>Workspace</span><strong>{task.workspace}</strong></div><div><span>Created</span><strong>{new Date(task.created_at).toLocaleString()}</strong></div><div><span>Agent</span><strong>Release Verification Agent</strong></div><button className="button button-secondary" onClick={onReport}>Open report</button></div><Timeline current={task.status} /></div>
    <div className="content-grid detail-grid"><div className="panel"><PanelTitle title={`Generated plan · Version ${plan?.version ?? '—'}`} action={plan ? plan.validation_status : 'No plan'} />{plan ? <div className="compact-plan">{plan.plan_json.resolved_steps.map((snapshot, index) => <div className="compact-step" key={snapshot.step_id}><span className="step-number">{index + 1}</span><div><strong>{snapshot.capability_id}</strong><span>{snapshot.resolved_tool_id} · {snapshot.resolved_action}</span></div><span>{Object.entries(snapshot.normalized_parameters).map(([key, value]) => `${key}: ${value}`).join(', ') || 'No parameters'}</span></div>)}</div> : <div className="empty-state">No validated plan yet.</div>}</div><div className="panel"><PanelTitle title="Evidence" action={`${detail.evidence.length} artifacts`} />{detail.evidence.length ? detail.evidence.map(item => <div className="evidence-row" key={item.id}><FileSearch size={16} /><div><strong>{item.summary}</strong><span>{item.artifact_path}</span></div></div>) : <div className="empty-state">Evidence will appear after approved execution.</div>}</div></div>
    <div className="content-grid detail-grid"><div className="panel"><PanelTitle title="Tool executions" action={`${detail.executions.length} recorded`} />{detail.executions.length ? detail.executions.map(item => <div className="execution-row" key={item.id}><span className={`execution-icon ${item.status.toLowerCase()}`}><Play size={14} /></span><div><strong>{item.tool_name} · {item.action}</strong><span>{item.result_summary ?? 'No result summary'}</span></div><StatusPill status={item.status} /></div>) : <div className="empty-state">No tool execution has started.</div>}</div><div className="panel"><PanelTitle title="Audit history" action={`${detail.audit.length} events`} />{detail.audit.map(item => <div className="audit-row" key={item.id}><History size={14} /><div><strong>{item.event_type.replaceAll('_', ' ')}</strong><span>{item.actor} · {item.payload_summary}</span></div><time>{new Date(item.created_at).toLocaleTimeString()}</time></div>)}</div></div>
  </section>
}
